# Generated by Django 2.0.5 on 2018-07-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicvideo',
            name='file',
            field=models.FileField(default='/', upload_to='music_videos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicvideo',
            name='duration',
            field=models.DurationField(default=0),
        ),
    ]
