# Generated by Django 2.0.5 on 2018-07-08 01:21

from django.db import migrations, models
import webplayer.models


class Migration(migrations.Migration):

    dependencies = [
        ('webplayer', '0002_auto_20180707_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicvideo',
            name='duration',
        ),
        migrations.AlterField(
            model_name='musicvideo',
            name='file',
            field=models.FileField(upload_to=webplayer.models.get_file_name),
        ),
    ]
