# Generated by Django 2.0.5 on 2018-07-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplayer', '0003_auto_20180707_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicvideo',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
